### ISSUE TITLE
Context Menus not consistent

### ISSUE THREAD

**Issue by Schwobaland** [sambalmueslie/LoanCalculator#28]
- when clicking on a founding there should be following entries:
  - "add loane"
  - "remove founding"
  - "edit founding"
  - "compare
  - and NO "Add founding"
- when clicking on empty space
  - "add loane"
  - "add founding" 
- when clicking on a loane
  - "remove loane"
  - "edit loane"
  - "compare"

**Comment by sambalmueslie** [comment]
having a default context menu with 
- Add new annuity loan
- Add new founding

Additional having when
- clicking on loan
  - Update <loan name>
  - Remove <loan name>
  - Compare <loan name>
- clicking on founding
  - Update <founding name>
  - Remove <founding name>
  - Compare <founding name>
