### ISSUE TITLE
Make tabs closeable and reopenable by entry tree

### ISSUE THREAD

**Issue by sambalmueslie** [sambalmueslie/LoanCalculator#31]
If you have many entries the tabs getting very confusing,
by allowing the user to close and reopen the tabs, he is able to decide.

**Comment by Schwobaland** [comment]
a better startup-performance would be reached, when tabs were closed on startup. By double-clicking on items in treepanel, the tab should be opened.

**Comment by sambalmueslie** [comment]
Done
